### ISSUE TITLE
Business Rule

### ISSUE THREAD

**Issue by NetoMouraJs** [OwnerCode/FilaFacil#4]

**Comment by FilipeNMarques** [comment]
**Fila Fácil**

 **ADM**

Um portal onde o cliente pode entrar, se cadastrar e utilizar o sistema em poucos minutos. Sem necessidade de custo adicional com instalação de equipamentos.
No portal o cliente escolhe um dos planos (discutir monetização), adiciona seus dados: numeros de sala, quichês, mesa, etc... Informações adicionais que vão passar no monitor ou tv e pronto. O sistema está pronto para uso.

**CLIENTE**

Um PWA ou APP que da acesso a todos os clientes do filá fácil. nele o cliente apenas com um simples cadastro, o cliente pode solicitar um ticket. (Dependendo da empresa  para solicitar o ticket o cliente pode adicionar algumas informações que possam agilizar o atendimento )

**Porque utilizar o FilaFácil?**

Com o FilaFácil, as empresas podem aumentar a previsibilidade da sua demanda. Agilizar o atendimento e melhorar os níveis de satisfação dos clientes. Além de conseguir ter métricas do seu atendimento, NPS, e muito mais.

**Comment by Fab2295** [comment]
**CLIENTE**

Um APP(salvo os casos de idosos) para cadastro de fila, onde conseguirá agendar consulta sem enfrentar fila. O App consiste no cadastro do cliente(validar se será do próprio consultório ou nosso) onde poderá reservar ticket no consultório e com possibilidade de CHECK-IN no aplicativo, caso o usuário se atrase, a vaga será dada para o usuário subsequente e ele será passado para o próximo da fila. Ao final da consulta será marcado como concluído e o sistema atualizará para o próximo da fila. 

**ÁREA ADMINISTRATIVA**
 Um portal para as empresas controlarem o fluxo de atendimento, check-in e check-out dos clientes.

**Comment by NetoMouraJs** [comment]
**Cliente**

O usuario que precisa enfrentar fila, ele poderá solicitar um ticket para uma fila o qual ele poderá  visualizar o tempo para atendimento (importante o check-in ate 5 mins antes do atendimento por conta das pessoas que nao tem app), ja as pessoas que não tem o app poderam solicitar o atendimento presencialmente com o atendente respeitando a ordem de solicitacao

**Admin**

Poderá  gerar ticket para fila (pessoas sem celular), visualizar tempo médio  de atendimento, gerenciar caixas ou salas para atendimento, controle de fluxo.

**Comment by lucas-marinoto** [comment]
**ADM**

Um portal onde o proprietário consegue saber quem sao as pessoas e senhas solicitadas e como esta o andamento do atendimento.

**CLIENTE**

PWA ou APP que auxilia na previsibilidade do tempo de fila para ambientes que não tem agendamento. O usuário pode instalar o app ou acessar o PWA e verificar quantas pessoas tem até o momento e quanto tempo esta demorando o atendimento médio.
O usuário poderá solicitar uma senha online e baseado no tempo que esta demorando o atendimento, o app irá informar em quantos minutos no máximo ele terá que chegar no local para ser atendido. 
Chegando no local, o usuário deverá fazer o checkin informando que esta la, caso a senha dele ja foi chamada, o mesmo será encaminhado para o final da fila, pois é necessário respeitar a fila dos que chegaram na hora correta.
Para as pessoas que não tem celular, será gerado uma senha no local e esta é integrada ao app, mas será encaixado por último da pessoa que fez o checkin (pois quem fez o ckeckin ja esta no local, para validar será pego via gps).

**Comment by NetoMouraJs** [comment]
**Ideia Fechada**

ADM
STOP > * controle de ambientes ( Salas, Caixas e etc.. )
 - Clinicas
 - Serviços de manutenção Automotiva
* Notificar todos os usuarios
* Gerenciamento de Reagendamento 

Cliente
STOP > * Listagem de Consultorios/Loterica (Credenciados)
* Lista Consultas marcadas
* Feedback do cliente
* Check-in
* Notificação de horario de check-in
* Reagendar Consulta
* Cancelar Senha
