### ISSUE TITLE
Pessoas sem celurares, teriam problemas?

### ISSUE THREAD

**Issue by NetoMouraJs** [OwnerCode/FilaFacil#6]
No caso, os idosos ou ate pessoas que não tem muita familiariade com celular

**Comment by FilipeNMarques** [comment]
Então, nesse caso as pessoas podem solicitar um ticket na recepção ou se a a clinica quiser, ela pode ocmprar monitores touch e a gente faz uma view  para gerar um ticker.

**Comment by lucas-marinoto** [comment]
Para lugares que tem fila indiana, uma solução (para uma soluçao mais elaborada e futura) é integrar uma camera, por exemplo do estabelecimento mesmo e esta reconhecer a fila e as pessoas que estao na mesma. E reconhecer tambem quando uma pessoa esta indo para o Caixa, acredito que isso consegue fazer um treinamento com e usar python para isto...

**Comment by Fab2295** [comment]
Da pra fazer fácil usando OpenCV da Intel com Python, mas acho que pra início deve pensar na ideia do Filipe, um ticket na recepção ou uma espécie de IPad como tem no Santander

**Comment by lucas-marinoto** [comment]
> Da pra fazer fácil usando OpenCV da Intel com Python, mas acho que pra início deve pensar na ideia do Filipe, um ticket na recepção ou uma espécie de IPad como tem no Santander

Sim sim, comentei mais para quando tiver algo amadurecido. É mais para não precisar de iteração humana e ser totalmente automatizado as coisas. Mas entendo que não é algo para agora e precisa ter customizações para ambientes diferentes
