### ISSUE TITLE
Technology - Class 

### ISSUE THREAD

**Issue by lucas-marinoto** [OwnerCode/FilaFacil#7]
Discussão sobre as classes do backend

**Comment by Fab2295** [comment]
**Seria legal a gente postar aqui o arquivo do proprio drawer.io para mostrar as classes**

**Comment by lucas-marinoto** [comment]
> **Seria legal a gente postar aqui o arquivo do proprio drawer.io para mostrar as classes**

https://drive.google.com/file/d/1FjIUkwZIeCtGiGJobbgHaVcQKxzXSiAd/view?usp=sharing

**Comment by Fab2295** [comment]
Eu estava fazendo o diagrama de classe do Fila fácil e me surgiu algumas dúvidas: 

**1. Quais informações são relevantes para o cadastro do usuário/cliente no sistema do ADM, fora nome, idade... será preciso peso, altura, cpf, endereço, etc..**

**2. O cliente poderá solicitar a deleção do seus dados no ADM do consultorio apartir do APP do cliente ?**

**3. Para o cadastro do funcionário quais serão informações importantes para criação ? Exemplo: cpf ?**

**4. O check-in poderá ser feito só pelo ADM ou as duas partes, cliente e adm ?**

**Comment by FilipeNMarques** [comment]
> Eu estava fazendo o diagrama de classe do Fila fácil e me surgiu algumas dúvidas:
> 
> **1. Quais informações são relevantes para o cadastro do usuário/cliente no sistema do ADM, fora nome, idade... será preciso peso, altura, cpf, endereço, etc..**

Podemos colocar, acho que não teria tanta diferença. Mas assim, seria mais um cadastro para as pessoas de recepção fazer, porque inicialmente nós só iremos  cuidar da filá, não vamos ser o CRM das empresas.
 
> **2. O cliente poderá solicitar a deleção do seus dados no ADM do consultorio apartir do APP do cliente ?**
> Tem que ter essa opção, para entramos na LGPD
> **3. Para o cadastro do funcionário quais serão informações importantes para criação ? Exemplo: cpf ?**
> Nada demaisl,  na minha opinião só o nome, email, cpf e senha.
> **4. O check-in poderá ser feito só pelo ADM ou as duas partes, cliente e adm ?**

Eu acho que pelas duas partes.

**Comment by Fab2295** [comment]
Por favor, se for criar os seus diagramas de classes no drawer.io, criem uma aba com seu nome

**Comment by NetoMouraJs** [comment]
Dá uma olhada ai lucas vê se precisamos acrescentar algo e se tiver duvida só falar

![Diagrama_sequecia-Diagrama - Fabrício](https://user-images.githubusercontent.com/34528933/71223472-dddd1c80-22b2-11ea-8fcf-48cefaa61dbb.png)
